image: registry.gitlab.fpcomplete.com/fpco/default-build-image:1954

cache:
  key: "$CI_BUILD_NAME"
  paths:
    - .stack-work/
    - .stack-root/

stages:
  - build

variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

build:
  stage: build
  only:
    - master
    - stable
  script:
    - export PATH=$HOME/.local/bin:$PATH
    - (cd etc/scripts && stack --install-ghc install --pedantic)
    - stack-release-script check

manual_build:
  stage: build
  when: manual
  script:
    - export PATH=$HOME/.local/bin:$PATH
    - (cd etc/scripts && stack --install-ghc install --pedantic)
    - stack-release-script check

docker_image_lts-9:
  stage: build
  when: manual
  script:
    - docker login -u "$PROD_DOCKER_USERNAME" -p "$PROD_DOCKER_PASSWORD"
    - etc/dockerfiles/stack-build/build.sh --push lts-9

docker_image_lts-10:
  stage: build
  when: manual
  script:
    - docker login -u "$PROD_DOCKER_USERNAME" -p "$PROD_DOCKER_PASSWORD"
    - etc/dockerfiles/stack-build/build.sh --push lts-10
