resolver: lts-10.5

# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
extra-deps:
- archive: https://github.com/commercialhaskell/rio/archive/c4d389fef57472bfd2e109a7c0d0624e95ca9281.tar.gz

# https://github.com/commercialhaskell/stack/issues/3785
- ansi-terminal-0.8.0.2@rev:0
- archive: https://github.com/haskell/hackage-security/archive/3297b0f3f4285cb30321baaa7b54e3d22e1f6bd7.tar.gz
  subdirs:
  - hackage-security
- Cabal-2.2.0.0@rev:1
- cabal-doctest-1.0.6@rev:1
- http-api-data-0.3.8@rev:0
