resolver: lts-10.5

# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
extra-deps:
- https://github.com/commercialhaskell/rio/archive/119cd7945e38b031c4251bae3e8a54ac9407d8c8.tar.gz

# https://github.com/commercialhaskell/stack/issues/3785
- ansi-terminal-0.8.0.1
- archive: https://github.com/haskell/hackage-security/archive/3297b0f3f4285cb30321baaa7b54e3d22e1f6bd7.tar.gz
  subdirs:
  - hackage-security
