resolver: lts-10.5

# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
extra-deps:
- git: https://github.com/commercialhaskell/rio
  commit: 09654f9fcbdcd96d0f5102796b32fdac5da7260e

# https://github.com/commercialhaskell/stack/issues/3785
- ansi-terminal-0.8.0.1
