resolver: lts-10.5
packages:
- .
- subs/rio

# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
extra-deps:
# https://github.com/commercialhaskell/stack/issues/3785
- ansi-terminal-0.8.0.1

# https://github.com/commercialhaskell/stack/issues/3073
- git: https://github.com/snoyberg/hackage-security
  commit: 61cd14609e5d7067e14469df31aafebfffda879c
  subdirs:
  - hackage-security
